<!DOCTYPE html>
<html lang="en">
<head>
<title>Fruteria el bosque</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="vista/bootstrap/js/bootstrap.min.js"></script>
</head>
<body>
<div class="container">
<header>

<?php include_once 'vista/html/header.php'; ?>

</header>
<?php include_once 'vista/html/menula.php'; ?>





<div class="col-sm-10 col-md-10"> <!—Columna de 10 espacios para contenido central e imágenes -->
<div class="panel panel-default">
<div class="panel-heading">
<h3 class="panel-title">Bienvenido, FRUTERIA EL BOSQUE</h3>
</div>
<div class="panel-body">
<p>DISFRUTE SU ESTADIA EN NUESTRA PAGINA... </p>
<div class="alert alert-success">
<div class="row">
<div class="col-md-3" align="center"> <span><img src="vista/imagenes/Ensalda1.jpg" width="100"
width="100"></span></div>
<div class="col-md-3" align="center"> <span><img src="vista/imagenes/ensalada2.jpg" width="100"
width="100"></span></div>
<div class="col-md-3" align="center"> <span><img src="vista/imagenes/emsalda3.jpg" width="130"
width="130"></span></div>
<div class="col-md-3" align="center"> <span><img src="vista/imagenes/ensalada4.jpg" width="110"
width="110"></span></div>

</div>
</div>
</div>
</div>
</div>
</div>

</div>
</body>
</html>